language: node_js
node_js:
- '6'
env:
  global:
    secure: E3YL9S41H65BLHfBUS46ZSZmKbjTFGePPf0YGqdDD8OHdigM6rm4DR3mvxqb57NnTqjW2oNV9gKpAvCxsqeOcxQykdBVyhpkq86+MPyH7FePJ6Gebd4Dns6tSQWC8SFns2Qf0gSQLm0HA6SsUXLvynNEl/WbkDyBP+E9H2zxtd0TDIe++O5ypfKfDhH0swxxkqw91YaE+sdFXyWudRljFpRGSL0VhwtLs8/4+rVt3g+U0szIdRIMCKb1nPsnJWpub9FgQOHGLfm8KTNjWr8OS8CtcaZtMZAT118FlaT2/tFAGAMeSz/fwBLR+tGgbZU95TvqiiMIzKgwKY764Bqa8K/rHiJfCCI8l+py5CJddnQEPFiBF9LXWUGVKwD/Ilj2v1ahh8AzXe+NOWkggzBqjw+N/21KYzCzQ4fz7E4I4VON8IPjqEfHDwlxNULqokb2Q0p+OB3e37uXbqg3nDKLfv22TaX63ubge/H1xyUh/0gCyRUXVo5edOOD6hYs3NKf7E1cY7z67xtQUhdnZdbHscEYi9SD1qV5M7mh3JDMFhsAQUxC0cjJ6cUmSqBA5OUOTq6MJFGirPXq8Z6+EBWDA1AH/q/X7riwRN7fck+RrxNt/WGAR5rpK3RSfVzsXdax95y5fQBjwzJKTaNVAzmUrZRuXi58qv5QCOphd7uUByo=
